service: serverless-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get